# Generated by Django 5.2.17 on 2026-09-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("casos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pergunta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ordem",
                    models.PositiveIntegerField(
                        help_text="Posição da tela dentro do caso."
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("informativa", "Informativa (texto ou texto + imagem)"),
                            ("so_imagem", "Somente imagem (com tempo de exibição)"),
                            (
                                "alternativas",
                                "Pergunta com alternativas (com timer, pontuada)",
                            ),
                            ("coleta_texto", "Coleta de dados: texto"),
                            ("coleta_numero", "Coleta de dados: número"),
                            (
                                "coleta_alternativas",
                                "Coleta de dados: alternativas (múltipla escolha, sem timer)",
                            ),
                            ("pontuacao", "Pontuação sem informações extras"),
                            ("pontuacao_extra", "Pontuação com conteúdo extra"),
                        ],
                        max_length=25,
                    ),
                ),
                ("titulo", models.CharField(blank=True, max_length=200)),
                ("texto", models.TextField(blank=True)),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="jogo/telas/"),
                ),
                (
                    "tempo_exibicao_segundos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "tempo_resposta_segundos",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "pontos_fixos",
                    models.IntegerField(
                        blank=True,
                        help_text="Pontuação fixa atribuída/perdida nesta tela (independente de resposta).",
                        null=True,
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perguntas",
                        to="casos.caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pergunta / Tela",
                "verbose_name_plural": "Perguntas / Telas",
                "ordering": ["caso", "ordem"],
                "unique_together": {("caso", "ordem")},
            },
        ),
        migrations.CreateModel(
            name="Jogada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_tentativa", models.PositiveIntegerField(default=1)),
                ("conta_para_ranking", models.BooleanField(default=True)),
                ("pontuacao", models.IntegerField(default=0)),
                ("finalizada", models.BooleanField(default=False)),
                ("iniciada_em", models.DateTimeField(auto_now_add=True)),
                ("finalizada_em", models.DateTimeField(blank=True, null=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jogadas",
                        to="casos.caso",
                    ),
                ),
                (
                    "pergunta_atual",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="jogo.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jogada",
                "verbose_name_plural": "Jogadas",
                "ordering": ["-iniciada_em"],
            },
        ),
        migrations.CreateModel(
            name="ConteudoExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("saiba_mais", "Saiba mais"),
                            ("legislacao", "Legislação"),
                            ("jurisprudencia", "Jurisprudência"),
                            ("questao_concurso", "Questão de concurso"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "texto",
                    models.TextField(help_text="Enunciado, texto legal, ementa etc."),
                ),
                (
                    "resposta",
                    models.TextField(
                        blank=True,
                        help_text="Usado apenas em QUESTAO_CONCURSO: a resposta revelada ao clicar em 'Ver resposta'.",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conteudos_extra",
                        to="jogo.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteúdo Extra",
                "verbose_name_plural": "Conteúdos Extra",
            },
        ),
        migrations.CreateModel(
            name="Alternativa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto", models.CharField(max_length=255)),
                (
                    "correta",
                    models.BooleanField(
                        default=False,
                        help_text="Usado apenas em telas do tipo ALTERNATIVAS.",
                    ),
                ),
                (
                    "pontos",
                    models.IntegerField(
                        default=0,
                        help_text="Pontos ganhos/perdidos ao escolher esta alternativa.",
                    ),
                ),
                ("ordem", models.PositiveIntegerField(default=0)),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternativas",
                        to="jogo.pergunta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alternativa",
                "verbose_name_plural": "Alternativas",
                "ordering": ["pergunta", "ordem"],
            },
        ),
        migrations.CreateModel(
            name="RespostaJogada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("texto_resposta", models.TextField(blank=True)),
                ("numero_resposta", models.FloatField(blank=True, null=True)),
                ("tempo_esgotado", models.BooleanField(default=False)),
                ("pontos_ganhos", models.IntegerField(default=0)),
                ("respondido_em", models.DateTimeField(auto_now_add=True)),
                (
                    "alternativas_selecionadas",
                    models.ManyToManyField(blank=True, to="jogo.alternativa"),
                ),
                (
                    "jogada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="respostas",
                        to="jogo.jogada",
                    ),
                ),
                (
                    "pergunta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="jogo.pergunta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resposta",
                "verbose_name_plural": "Respostas",
                "ordering": ["respondido_em"],
            },
        ),
    ]
