services:
  - type: web
    name: jogo-advogado
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "0"
      - key: DB_ENGINE
        value: "sqlite"
      - key: PYTHON_VERSION
        value: "3.12.4"