# Generated by Django 5.2.17 on 2026-09-06 13:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Disciplina",
                "verbose_name_plural": "Disciplinas",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Caso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "texto_curto",
                    models.CharField(
                        help_text="Texto curto exibido na tela principal (lista de casos).",
                        max_length=280,
                    ),
                ),
                (
                    "texto_detalhado",
                    models.TextField(
                        help_text="Texto maior, exibido na tela de detalhamento do caso."
                    ),
                ),
                (
                    "imagem_capa",
                    models.ImageField(blank=True, null=True, upload_to="casos/capas/"),
                ),
                (
                    "tipo_acesso",
                    models.CharField(
                        choices=[("gratis", "Grátis"), ("premium", "Premium")],
                        default="gratis",
                        max_length=10,
                    ),
                ),
                (
                    "tipo_caso",
                    models.CharField(
                        choices=[("parcial", "Parcial"), ("completo", "Completo")],
                        max_length=10,
                    ),
                ),
                (
                    "duracao",
                    models.CharField(
                        choices=[
                            ("curta", "Curta"),
                            ("media", "Média"),
                            ("longa", "Longa"),
                        ],
                        max_length=10,
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "disciplina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="casos",
                        to="casos.disciplina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso",
                "verbose_name_plural": "Casos",
                "ordering": ["-criado_em"],
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "caso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="avaliacoes",
                        to="casos.caso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avaliação",
                "verbose_name_plural": "Avaliações",
                "unique_together": {("caso", "aluno")},
            },
        ),
    ]
