# Generated by Django 6.1.1 on 2026-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='destaque_area_gratuita',
            field=models.BooleanField(default=False, help_text='Aparece na área gratuita do site institucional (curadoria manual, independente do tipo_acesso).'),
        ),
    ]
