# Generated by Django 5.2.17 on 2026-09-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InstituicaoEnsino",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=255)),
                (
                    "estado",
                    models.CharField(help_text="UF, ex.: SP, RJ, TO", max_length=2),
                ),
            ],
            options={
                "verbose_name": "Instituição de Ensino",
                "verbose_name_plural": "Instituições de Ensino",
                "ordering": ["nome"],
                "unique_together": {("nome", "estado")},
            },
        ),
        migrations.CreateModel(
            name="Perfil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_jogador", models.CharField(max_length=100)),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatares/"),
                ),
                ("endereco", models.CharField(blank=True, max_length=255)),
                ("receber_notificacoes", models.BooleanField(default=True)),
                ("receber_newsletter", models.BooleanField(default=True)),
                ("pontuacao_total", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "instituicao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alunos",
                        to="contas.instituicaoensino",
                    ),
                ),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil",
                "verbose_name_plural": "Perfis",
            },
        ),
    ]
