# Generated by Django 5.2.17 on 2026-09-06 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanoPremium",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                (
                    "duracao_dias",
                    models.PositiveIntegerField(help_text="Duração do plano em dias."),
                ),
                (
                    "preco_centavos",
                    models.PositiveIntegerField(help_text="Preço em centavos."),
                ),
                ("ativo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Plano Premium",
                "verbose_name_plural": "Planos Premium",
            },
        ),
        migrations.CreateModel(
            name="Assinatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateField()),
                ("fim", models.DateField()),
                ("ativa", models.BooleanField(default=True)),
                ("criada_em", models.DateTimeField(auto_now_add=True)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assinaturas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plano",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="premium.planopremium",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assinatura",
                "verbose_name_plural": "Assinaturas",
                "ordering": ["-criada_em"],
            },
        ),
    ]
