# Generated by Django 5.2.17 on 2026-09-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("premium", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planopremium",
            name="preco_centavos",
        ),
        migrations.AddField(
            model_name="planopremium",
            name="preco",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
