# Generated by Django 5.2.17 on 2026-09-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_masculino", models.CharField(max_length=50)),
                ("nome_feminino", models.CharField(max_length=50)),
                (
                    "pontuacao_minima",
                    models.PositiveIntegerField(
                        help_text="Pontuação mínima para atingir este nível."
                    ),
                ),
            ],
            options={
                "verbose_name": "Nível",
                "verbose_name_plural": "Níveis",
                "ordering": ["pontuacao_minima"],
            },
        ),
    ]
